In [1]:
import numpy as np
from scipy.signal import convolve2d

In [2]:
image = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

filtr = np.array([[-1, -2, -1],
                  [0, 0, 0],
                  [1, 2, 1]])
image.shape

(3, 3)

In [3]:
filtr

array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  2,  1]])

In [4]:
np.rot90(filtr, k=2) # rotate 180 degree

array([[ 1,  2,  1],
       [ 0,  0,  0],
       [-1, -2, -1]])

In [5]:
def conv2d(image, filtr, mode = 'same'):
    filtr = np.rot90(filtr, 2) # rotate 180 degree
    image_row, image_col = image.shape
    filtr_row, filtr_col = filtr.shape
    if mode == 'full':
        zeros = np.zeros((filtr_row-1, image_col))
        extimg = np.vstack((zeros, image, zeros))
        zeros = np.zeros((extimg.shape[0], filtr_col-1))
        extimg = np.column_stack((zeros, extimg, zeros))
    elif mode == 'same':
        zeros = np.zeros((int(filtr_row/2), image_col))
        extimg = np.vstack((zeros, image, zeros))
        zeros = np.zeros((extimg.shape[0], int(filtr_col/2)))
        extimg = np.column_stack((zeros, extimg, zeros))
    else:
        extimg = image
        
    print(extimg)
        
    row_start, row_end = 0, extimg.shape[0]-filtr.shape[0]+1
    col_start, col_end = 0, extimg.shape[1]-filtr.shape[1]+1
    result = np.zeros((row_end, col_end))
    for r in range(row_start, row_end):
        for c in range(col_start, col_end):
            cur_region = extimg[r:r+filtr_row, c:c+filtr_col]
            result[r, c] = np.sum(cur_region * filtr)
    return result

In [6]:
conv2d(image, filtr, mode='valid'), "vs", convolve2d(image, filtr, mode='valid')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([[-24.]]), 'vs', array([[-24]]))

In [7]:
conv2d(image, filtr, mode='same')

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


array([[-13., -20., -17.],
       [-18., -24., -18.],
       [ 13.,  20.,  17.]])

In [8]:
convolve2d(image, filtr, mode='same', boundary='fill', fillvalue=0)

array([[-13, -20, -17],
       [-18, -24, -18],
       [ 13,  20,  17]])

In [9]:
conv2d(image, filtr, mode='full')

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0. 0.]
 [0. 0. 4. 5. 6. 0. 0.]
 [0. 0. 7. 8. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[ -1.,  -4.,  -8.,  -8.,  -3.],
       [ -4., -13., -20., -17.,  -6.],
       [ -6., -18., -24., -18.,  -6.],
       [  4.,  13.,  20.,  17.,   6.],
       [  7.,  22.,  32.,  26.,   9.]])

In [10]:
convolve2d(image, filtr, mode='full', boundary='fill', fillvalue=0)

array([[ -1,  -4,  -8,  -8,  -3],
       [ -4, -13, -20, -17,  -6],
       [ -6, -18, -24, -18,  -6],
       [  4,  13,  20,  17,   6],
       [  7,  22,  32,  26,   9]])

# Conv full



In [11]:
# np.convolve(a=image, v=filtr, mode='full')

In [12]:
A = np.array([[17, 24, 1, 8, 15],
              [23, 5, 7, 14, 16],
              [4, 6, 13, 20, 22],
              [10, 12, 19, 21, 3],
              [11, 18, 25, 2, 9]], dtype=np.int)

V = np.array([[1, 3, 1], [0, 5, 0], [2, 1, 2]], dtype=np.int)

In [13]:
convolve2d(A, V, mode='full', boundary='fill', fillvalue=0)

array([[ 17,  75,  90,  35,  40,  53,  15],
       [ 23, 159, 165,  45, 105, 137,  16],
       [ 38, 198, 120, 165, 205, 197,  52],
       [ 56,  95, 160, 200, 245, 184,  35],
       [ 19, 117, 190, 255, 235, 106,  53],
       [ 20,  89, 160, 210,  75,  90,   6],
       [ 22,  47,  90,  65,  70,  13,  18]])

In [14]:
convolve2d(A, V, mode='same', boundary='fill', fillvalue=0)

array([[159, 165,  45, 105, 137],
       [198, 120, 165, 205, 197],
       [ 95, 160, 200, 245, 184],
       [117, 190, 255, 235, 106],
       [ 89, 160, 210,  75,  90]])

In [15]:
convolve2d(A, V, mode='valid', boundary='fill', fillvalue=0)

array([[120, 165, 205],
       [160, 200, 245],
       [190, 255, 235]])

In [16]:
conv2d(A, V, mode='full')

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 17. 24.  1.  8. 15.  0.  0.]
 [ 0.  0. 23.  5.  7. 14. 16.  0.  0.]
 [ 0.  0.  4.  6. 13. 20. 22.  0.  0.]
 [ 0.  0. 10. 12. 19. 21.  3.  0.  0.]
 [ 0.  0. 11. 18. 25.  2.  9.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


array([[ 17.,  75.,  90.,  35.,  40.,  53.,  15.],
       [ 23., 159., 165.,  45., 105., 137.,  16.],
       [ 38., 198., 120., 165., 205., 197.,  52.],
       [ 56.,  95., 160., 200., 245., 184.,  35.],
       [ 19., 117., 190., 255., 235., 106.,  53.],
       [ 20.,  89., 160., 210.,  75.,  90.,   6.],
       [ 22.,  47.,  90.,  65.,  70.,  13.,  18.]])

In [17]:
conv2d(A, V, mode='same')

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0. 17. 24.  1.  8. 15.  0.]
 [ 0. 23.  5.  7. 14. 16.  0.]
 [ 0.  4.  6. 13. 20. 22.  0.]
 [ 0. 10. 12. 19. 21.  3.  0.]
 [ 0. 11. 18. 25.  2.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


array([[159., 165.,  45., 105., 137.],
       [198., 120., 165., 205., 197.],
       [ 95., 160., 200., 245., 184.],
       [117., 190., 255., 235., 106.],
       [ 89., 160., 210.,  75.,  90.]])

In [18]:
conv2d(A, V, mode='valid')

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


array([[120., 165., 205.],
       [160., 200., 245.],
       [190., 255., 235.]])