# <div align="center"> numpy.where </div>

In [1]:
import numpy as np

# np.where(condition, x, y)
# x,y 同时存在, 同时去掉
# x: select element from x if true
# y: select element from y if false

In [4]:
# Case-1

result = np.where([True, False, False], [1, 2, 4], [7, 8, 9])
result

array([1, 8, 9])

In [5]:
# Case-2-1 (全参数)

arr = np.array([11, 12, 13])
result = np.where(arr < 12, [1, 2, 4], [7, 8, 9])
result

array([1, 8, 9])

In [25]:
# Case-2-2 (全参数)

arr = np.arange(10)
result = np.where(arr > 4, 1, -1)
print(arr, result, sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1 -1  1  1  1  1  1]


In [26]:
# Case-3 (非全参数)

arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
result = np.where((arr > 12) & (arr < 16))
# 返回的是true(符合条件)arr的下标
print(result, arr[np.where((arr > 12) & (arr < 16))[0]], sep='\n')

(array([ 2,  3,  4,  7, 10, 11]),)
[13 14 15 15 14 15]


In [29]:
# Case-4 (二维)

result = np.where([[True, False], [True, True]], 
         [[1,2], [3,4]], [[9,8], [7,6]])

# 第一维[True, False], 从[1,2], [9,8]选择: 从 x中第一维选择1, 从 y中第一维选择8
# 第二维[True, True], 从[3,4], [7,6]选择: 从 x中第二维选择3, 从 x中第二维选择4
# 三个参数的size必须一致
result

array([[1, 8],
       [3, 4]])

In [30]:
# Case-5 (三维)

arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
arr > 5

array([[[False, False, False],
        [False, False, False],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [32]:
np.where(arr > 5)

(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [37]:
arr[0][2][0], arr[0][2][1], arr[0][2][2]

(6, 7, 8)