# <div align='center'> Latex of Product </div>

In [1]:
import numpy as np

In [2]:
def print_matrix(M):
    for row in M:
        for val in row:
            print('{:4}'.format(val), end=' ')
        print('')

In [3]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

In [4]:
print_matrix(a)
print('')
print_matrix(b)

   1    2 
   3    4 

   5    6 
   7    8 


## 向量

### 叉乘

cross prodcut, latex: $\times$

向量积、矢积、叉乘、外积 

求法线

In [5]:
np.cross([1, 2, 3], [4, 5, 6])
# 1i + 2j + 3k
# 4i + 5j + 6k
# [2*6 - 3*5, 3*4 - 1*6, 1*5 - 2*4]

array([-3,  6, -3])

In [6]:
np.cross(a, b)
# TODO
# (1, 2)(7, 8) - (5, 6)(3, 4)
# (7, 16) - (15, 24)
# (7-15, 16-24) ???

array([-4, -4])

### 点乘 inner product

dot product, scalar product, latex: $\bullet$

向量点积 $<\mathbf u \mathbf v> = \mathbf{u}^T \mathbf v$

In [7]:
np.dot([1, 2, 3], [4, 5, 6])
# 1*4 + 2*5 + 3*6 = 32

32

In [8]:
print_matrix(a)
print('')
print_matrix(b)

np.dot(a, b)
# [[(1,2)(5,7), (1,2)(6,8)], [(3,4)(5,7), (3,4)(6,8)]]
# [[19, 22], [43, 50]]

   1    2 
   3    4 

   5    6 
   7    8 


array([[19, 22],
       [43, 50]])

### 外积 outer product 

outer product, latex: $\otimes \ or\ \otimes_{outer}$

向量外积 $\mathbf u \otimes \mathbf v = \mathbf u \mathbf{v}^T$

In [10]:
u = np.array([1, 2, 3])
v = np.array([4, 5])
np.outer(u, v)

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [11]:
np.kron(u, v) # The Kronecker product is a form of vectorization (or flattening) of the outer product. 

array([ 4,  5,  8, 10, 12, 15])

## 矩阵

## 克罗内克积

latex: $\otimes \ or \ \otimes_{kron}$

In [12]:
print_matrix(a)
print_matrix(b)
np.kron(a, b)

   1    2 
   3    4 
   5    6 
   7    8 


array([[ 5,  6, 10, 12],
       [ 7,  8, 14, 16],
       [15, 18, 20, 24],
       [21, 24, 28, 32]])

## 哈达玛积

Hadamard product, latex:$\circ$ 

基本积, element-wise multiply

$A*B , A \circ B, A \odot B$

当矩阵是numpy.ndarray时


In [13]:
print(type(a), type(b))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
b

array([[5, 6],
       [7, 8]])

In [16]:
a*b

array([[ 5, 12],
       [21, 32]])

### 矩阵乘积

matmul product

$AB, A \cdot B, A_{ik}B_{kj}$

当矩阵是numpy.matrix时, 都是**\***号,但结果不同

dot, matmul

In [17]:
c = np.matrix(a)
d = np.matrix(b)
print(type(c), type(d))

<class 'numpy.matrix'> <class 'numpy.matrix'>


In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
b

array([[5, 6],
       [7, 8]])

In [20]:
c

matrix([[1, 2],
        [3, 4]])

In [21]:
d

matrix([[5, 6],
        [7, 8]])

In [22]:
c*d
# 1*5 + 2*7 | 1*6 + 2*8
# 3*5 + 4*7 | 3*6 + 4*8

matrix([[19, 22],
        [43, 50]])

In [23]:
a*b

array([[ 5, 12],
       [21, 32]])

In [24]:
np.dot(c, d)

matrix([[19, 22],
        [43, 50]])

In [25]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [26]:
np.matmul(c, d)

matrix([[19, 22],
        [43, 50]])

In [27]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])