# <div align='center'> Latex of Product </div>

In [3]:
import numpy as np 

In [20]:
def print_matrix(M):
    for row in M:
        for val in row:
            print('{:4}'.format(val), end=' ')
        print('')

In [21]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

In [34]:
print_matrix(a)
print('')
print_matrix(b)

   1    2 
   3    4 

   5    6 
   7    8 


## 向量

### 叉乘

cross prodcut, latex: $\times$

向量积、矢积、叉乘、外积 

求法线

In [30]:
np.cross([1, 2, 3], [4, 5, 6])
# 1i + 2j + 3k
# 4i + 5j + 6k
# [2*6 - 3*5, 3*4 - 1*6, 1*5 - 2*4]

array([-3,  6, -3])

In [31]:
np.cross(a, b)
# TODO
# (1, 2)(7, 8) - (5, 6)(3, 4)
# (7, 16) - (15, 24)
# (7-15, 16-24) ???

array([-4, -4])

### 点乘

dot product, scalar product, latex: $\bullet$

向量点积

In [32]:
np.dot([1, 2, 3], [4, 5, 6])
# 1*4 + 2*5 + 3*6 = 32

32

In [36]:
np.dot(a, b)
# [[(1,2)(5,7), (1,2)(6,8)], [(3,4)(5,7), (3,4)(6,8)]]
# [[19, 22], [43, 50]]

array([[19, 22],
       [43, 50]])

## 矩阵

## 克罗内克积

latex: $\bigotimes$

In [38]:
print_matrix(a)
print_matrix(b)
np.kron(a, b)

   1    2 
   3    4 
   5    6 
   7    8 


array([[ 5,  6, 10, 12],
       [ 7,  8, 14, 16],
       [15, 18, 20, 24],
       [21, 24, 28, 32]])

## 哈达玛积

Hadamard product, latex:$\circ$ 

基本积, element-wise multiply

$A*B , A \circ B$

当矩阵是numpy.ndarray时


In [53]:
print(type(a), type(b))
a*b

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
   1    2 
   3    4 
   5    6 
   7    8 


array([[ 5, 12],
       [21, 32]])

### 矩阵乘积

matmul product

$AB$

当矩阵是numpy.matrix时, 都是**\***号,但结果不同

In [48]:
c = np.matrix(a)
d = np.matrix(b)
print(type(c), type(d))
c*d, np.dot(c, d), np.matmul(c, d), np.dot(a, b), np.matmul(a, b), a*b

<class 'numpy.matrix'> <class 'numpy.matrix'>


(matrix([[19, 22],
         [43, 50]]), matrix([[19, 22],
         [43, 50]]), matrix([[19, 22],
         [43, 50]]), array([[19, 22],
        [43, 50]]), array([[19, 22],
        [43, 50]]), array([[ 5, 12],
        [21, 32]]))